# Generated by Django 4.0.2 on 2022-02-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, verbose_name='Uname')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phonenumber')),
            ],
        ),
        migrations.DeleteModel(
            name='telegram_user',
        ),
    ]
